name: travel-thing-frontend
services:
  - name: web
    source_dir: travel-thing
    github:
      repo: https://github.com/crisanalex15/TT-frontend
      branch: main
    build_command: npm install && npm run build
    run_command: npm run serve
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: HOST
        value: "0.0.0.0"
